version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 230999
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db: