# Generated by Django 4.1.1 on 2022-10-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorinfo',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
