# Generated by Django 4.1.1 on 2022-10-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'Черновик'), ('Published', 'Опубликовано')], default='Draft', max_length=10),
        ),
    ]
