# Generated by Django 4.1.5 on 2023-01-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="send_comment_on_post_notification",
            field=models.BooleanField(default=False),
        ),
    ]
