# Generated by Django 4.1.5 on 2023-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_pic",
            field=models.ImageField(blank=True, null=True, upload_to="user_post_pictures"),
        ),
    ]
